services:
  trino:
    image: 'trinodb/trino:478'
    hostname: trino
    container_name: trino
    ports:
      - '8085:8080'
    volumes:
      - ./etc:/etc/trino
      - ./hadoop_config:/etc/hadoop/conf
    environment:
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - bdfp-net

networks:
  bdfp-net:
    external: true
